### ISSUE TITLE
support for native s390x runners

### ISSUE THREAD

**Issue by chantra** [kernel-patches/runner#7]
Currently the only way to run s390x runners is by running them under qemu, this is **super** slow and cause the whole CI pipeline to take longer than it should.

Having native support for s390x would help shave time of as well as having a leaner worker.
Currently, we can pull actions/runner repo, patch it manually, and compile it, but this is not sustainable.

actions/runner#2263 would add support so we could easily build actions-runner for s390x and create a runner that is readily available for s390x.

**Comment by chantra** [comment]
Forgot to reply to this....
Thanks @ChristopherHX for the suggestion. Last I had tried https://github.com/nektos/act, mostly in order to be able to quickly run a workflow locally, it did not work out out of the box. I will try to put some more time into it.

**Comment by iii-i** [comment]
zlib-ng has moved from the runner emulation setup to https://github.com/anup-kodlekere/gaplib now; you can check out the https://github.com/zlib-ng/zlib-ng/pull/1716 PR for details.

**Comment by chantra** [comment]
Thanks for the FYI. I am planning to migrate to 24.04 first but then running natively could be a nice follow-up.
